---
- name: Copy authorized_keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: /home/ich/.ssh/authorized_keys
    owner: ich
    group: ich
    mode: "0600"

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"

- name: Change SSH port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port 4242"
