---
- name: Update apt install
  ansible.builtin.apt:
    update_cache: yes

- name: Install useful packages
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - nano
    update_cache: yes
