#!/bin/bash

if [[ -d ~/.zsh ]]; then
  gum confirm "ZSH is already installed. Do you want to reinstall it?" || exit 0
  echo "Removing existing ZSH configuration..."
  rm -rf ~/.zsh ~/.p10k.zsh ~/.zshrc ~/.zprofile
fi

echo "Installing ZSH..."
if gum spin --title "apt install zsh -y" -- apt install zsh -y; then
  echo "✅ ZSH installed."
else
  echo "❌ Failed to install ZSH."
  exit 1
fi

echo "Setting up ZSH..."
if mkdir -p /usr/local/etc/dotfile \
   && cp dotfiles/.p10k.zsh dotfiles/.zshrc dotfiles/.zprofile /usr/local/etc/dotfile \
   && mkdir -p /usr/local/etc/dotfile/.zsh \
   && cd /usr/local/etc/dotfile/.zsh \
   && gum spin --title "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git" -- git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
   && gum spin --title "git clone https://github.com/zsh-users/zsh-autosuggestions" -- git clone https://github.com/zsh-users/zsh-autosuggestions \
   && gum spin --title "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git" -- git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
   && (rm /root/.p10k.zsh; ln /usr/local/etc/dotfile/.p10k.zsh /root/.p10k.zsh) \
   && (rm /root/.zshrc; ln /usr/local/etc/dotfile/.zshrc /root/.zshrc) \
   && (rm /root/.zprofile; ln /usr/local/etc/dotfile/.zprofile /root/.zprofile) \
   && (rm /root/.zsh; ln -s /usr/local/etc/dotfile/.zsh /root/.zsh) \
   && (rm /home/ich/.p10k.zsh; ln /usr/local/etc/dotfile/.p10k.zsh /home/ich/.p10k.zsh) \
   && (rm /home/ich/.zshrc; ln /usr/local/etc/dotfile/.zshrc /home/ich/.zshrc) \
   && (rm /home/ich/.zprofile; ln /usr/local/etc/dotfile/.zprofile /home/ich/.zprofile) \
   && (rm /home/ich/.zsh; ln -s /usr/local/etc/dotfile/.zsh /home/ich/.zsh);
then
  echo "✅ ZSH setup completed."
else
  echo "❌ Failed to set up ZSH."
  exit 1
fi

if [[ $YES_TO_ALL = true ]] || gum confirm "Do you want to add some common aliases?"; then
  echo 'alias l="ls -l"' > /usr/local/etc/sh/90_aliases_common.sh
  echo 'alias ll="ls -lah"' >> /usr/local/etc/sh/90_aliases_common.sh
  echo 'alias source-zsh="source ~/.zshrc"' >> /usr/local/etc/sh/90_aliases_common.sh
  echo 'alias nano-zsh="nano ~/.zshrc && source-zsh"' >> /usr/local/etc/sh/90_aliases_common.sh
  chmod +x /usr/local/etc/sh/90_aliases_common.sh

  echo "✅ Aliases added."
fi;

echo "Switching to ssh..."
chsh -s $(which zsh)
sudo -u ich chsh -s $(which zsh)