- name: Install node for 'root'
  ansible.builtin.include_role:
    name: morgangraphics.ansible-role-nvm
  vars:
    nvm_dir: "/root/.nvm"

- name: Install latest Node.js for 'root'
  ansible.builtin.shell: |
    export NVM_DIR=/root/.nvm
    . "$NVM_DIR/nvm.sh"
    nvm install node
  args:
    executable: /usr/bin/zsh

- name: Install node for 'ich'
  ansible.builtin.include_role:
    name: morgangraphics.ansible-role-nvm
  vars:
    nvm_dir: "/home/ich/.nvm"

- name: Ensure .nvm directory ownership is ich:ich
  ansible.builtin.file:
    path: /home/ich/.nvm
    owner: ich
    group: ich
    recurse: yes

- name: Install latest Node.js for 'ich'
  become_user: ich
  ansible.builtin.shell: |
    export NVM_DIR=/home/ich/.nvm
    . "$NVM_DIR/nvm.sh"
    nvm install node
  args:
    executable: /usr/bin/zsh

- name: Copy nvm setup script
  ansible.builtin.copy:
    src: "50_nvm"
    dest: "{{ shell_files_dest }}/50_nvm"
    mode: "777"
    owner: root
    group: sysconf
