#!/bin/bash

alias d="sudo docker"
alias c="d compose"
alias cl="c logs -f"
alias cu="c up -d --build"
alias cul="cu && cl"
alias cr="c down && c up -d --build"
alias crl="cr && cl"
alias ce="c exec"
alias cei="ce -it"