---
- name: Base server setup
  hosts: all
  become: yes

  vars:
    dotfiles_dest: /usr/local/etc/dotfiles
    shell_files_dest: /usr/local/etc/sh
    bin_files_dest: /usr/local/bin
    srv_root: /srv

  roles:
    - setup
    - nginx
    - zsh
    - node
    - eza
    - zoxide
    - docker
    - fastfetch
