---
- name: Base server setup
  hosts: all
  become: yes

  vars:
    dotfiles_dest: /usr/local/etc/dotfiles
    shell_files_dest: /usr/local/etc/sh
    bin_files_dest: /usr/local/bin
    srv_root: /srv
    services_root: /opt
    email: mehmedovic.ilijaz@gmail.com

  roles:
    - setup
    - zsh
    - rust
    - node
    - docker
    - nginx
    - eza
    - zoxide
    - fzf
    - zellij
    - nvchad
    - fastfetch
