#!/bin/bash

echo "Installing docker..."
if gum spin --title "for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do apt-get remove $pkg; done" -- sh -c "for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do apt-get remove $pkg; done" \
   && gum spin --title "apt-get install ca-certificates -y" -- apt-get install ca-certificates -y \
   && gum spin --title "install -m 0755 -d /etc/apt/keyrings" -- install -m 0755 -d /etc/apt/keyrings \
   && gum spin --title "curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc" -- curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
   && chmod a+r /etc/apt/keyrings/docker.asc \
   && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
   && gum spin --title "apt-get update" -- apt-get update \
   && gum spin --title "apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y" -- apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y;
then
  echo "✅ Docker installed"
else
  echo "❌ Failed to install docker."
  exit 1
fi

if gum confirm "Do you want to add some docker aliases?"; then
  echo 'alias d="docker"' > /usr/local/etc/sh/90_aliases_docker.sh
  echo 'alias c="d compose"' >> /usr/local/etc/sh/90_aliases_docker.sh
  echo 'alias cu="c up --build -d"' >> /usr/local/etc/sh/90_aliases_docker.sh
  echo 'alias cr="c down && cu"' >> /usr/local/etc/sh/90_aliases_docker.sh
  echo 'alias cl="c logs -f"' >> /usr/local/etc/sh/90_aliases_docker.sh
  echo 'alias crl="cr && cl"' >> /usr/local/etc/sh/90_aliases_docker.sh

  echo "✅ Aliases added."
fi;