#!/bin/bash

echo "Installing fastfetch..."
if gum spin --title "apt update" -- apt update \
   && gum spin --title "apt install fastfetch -y" -- apt install fastfetch -y;
then
  echo "✅ fastfetch installed."
else
  echo "❌ Failed to install fastfetch."
  exit 1
fi

if [[ $YES_TO_ALL = true ]] || gum confirm "Do you want to execute fastfetch on startup as a non root user?";
then
  echo "if [ \"\$EUID\" -eq 0 ]; then :; else fastfetch; fi" > /usr/local/etc/sh/00_startup_01_fastfetch.sh
  chmod +x /usr/local/etc/sh/00_startup_01_fastfetch.sh
fi