#!/bin/bash

echo "Installing nvm..."
if gum spin --title "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash" -- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \
   && \. "$HOME/.nvm/nvm.sh";
then
  echo "✅ node.js installed"^
else
  echo "❌ Failed to install node.js."
  exit 1
fi

echo "Init nvm..."
echo "export NVM_DIR=\"\$HOME/.nvm\"" > /usr/local/etc/sh/80_nvm.sh
echo "[ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\"" >> /usr/local/etc/sh/80_nvm.sh
echo "[ -s \"\$NVM_DIR/bash_completion\" ] && \\. \"\$NVM_DIR/bash_completion\"" >> /usr/local/etc/sh/80_nvm.sh
chmod +x /usr/local/etc/sh/80_nvm.sh
source /usr/local/etc/sh/80_nvm.sh

echo "Installing node.js..."
if ([ $YES_TO_ALL = true ] && echo "22" || gum choose --header="Choose node version to install" --selected="22" "18" "20" "22" "24") \
   | xargs -I{} bash -c 'gum spin --title "nvm install {}" -- bash -c "source /usr/local/etc/sh/80_nvm.sh && nvm install {}"';
then
  echo "✅ node.js installed"^
else
  echo "❌ Failed to install node.js."
  exit 1
fi