#!/bin/bash

if [[ -d ~/.zsh ]]; then
  gum confirm "ZSH is already installed. Do you want to reinstall it?" || exit 0
  echo "Removing existing ZSH configuration..."
  rm -rf ~/.zsh ~/.p10k.zsh ~/.zshrc ~/.zprofile
fi

if [[ -d /usr/local/etc/zsh ]]; then
  mkdir /usr/local/etc/zsh
fi

echo "Installing ZSH..."
if gum spin --title "apt install zsh -y" -- apt install zsh -y; then
  echo "✅ ZSH installed."
else
  echo "❌ Failed to install ZSH."
  exit 1
fi

echo "Setting up ZSH..."
if cp dotfiles/.p10k.zsh dotfiles/.zshrc dotfiles/.zprofile ~/ \
   && mkdir -p ~/.zsh \
   && cd ~/.zsh/ \
   && gum spin --title "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git" -- git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
   && gum spin --title "git clone https://github.com/zsh-users/zsh-autosuggestions" -- git clone https://github.com/zsh-users/zsh-autosuggestions \
   && gum spin --title "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git" -- git clone https://github.com/zsh-users/zsh-syntax-highlighting.git;
then
  echo "✅ ZSH setup completed."
else
  echo "❌ Failed to set up ZSH."
  exit 1
fi

if gum confirm "Do you want to add some common aliases?"; then
  echo "" > /usr/local/etc/zsh/90_aliases_common.zsh
  echo -e 'alias l="ls -l"\n' >> /usr/local/etc/zsh/90_aliases_common.zsh
  echo -e 'alias ll="ls -lah"\n' >> /usr/local/etc/zsh/90_aliases_common.zsh

  echo "✅ Aliases added."
fi;
